name: CI - Build backend

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
     postgres:
      image: postgres:17.1
      env:
        POSTGRES_USER: amigoscode
        POSTGRES_PASSWORD: password
        POSTGRES_DB: customer
      ports:
        - 5332:5432
      options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        working-directory: spring-boot-example
        run: mvn -ntp -B verify
